
            var _listEvents			= [];
			var _type 				= 'livetv';
			var _currData 			= '';
			var _idIptv				= '408';
			var _idEvent			= '0';
			var _intervalPlay 		= null;
			var _simmerTv			=  '<div class="card-box">';
				_simmerTv			+= '<div class="wrapper-box">';
				_simmerTv			+= '  <div class="pic-box animate"></div>';
				_simmerTv			+= '  <div class="right-box">';
				_simmerTv			+= '	<div class="simmer-text br animate w150"></div>';		  
				_simmerTv			+= '	<div class="simmer-text br animate w70"></div>';
				_simmerTv			+= '  </div>';
			    _simmerTv			+= '</div>';
				_simmerTv			+= '</div>';
				
			var _simmerEvent		 = '<div class="card-box">';
				_simmerEvent		+= '<div class="simmer-text br animate w150"></div>';
				_simmerEvent		+= '<div class="simmer-text-mini br animate w170"></div>';
			    _simmerEvent		+= '<div class="wrapper-box">';
				_simmerEvent		+= '  <div class="w200">';
				_simmerEvent		+= '	<div class="simmer-text br animate w60"></div>';
				_simmerEvent		+= '	<div class="simmer-text br animate w60"></div>';
				_simmerEvent		+= '  </div>';
				_simmerEvent		+= '  <div class="right-box" style="text-align: right">';
				_simmerEvent		+= '	<div class="simmer-text br animate w30"></div>';
				_simmerEvent		+= '	<div class="simmer-text br animate w50"></div>';
				_simmerEvent		+= '  </div>';
			    _simmerEvent		+= '</div>';
				_simmerEvent		+= '</div>';	
